apiVersion: v1
kind: Service
metadata:
  name: darwin-scaffold-studio
  namespace: darwin-scaffold-studio
  labels:
    app: darwin-scaffold-studio
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 8600
    targetPort: 8600
    protocol: TCP
  - name: metrics
    port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: darwin-scaffold-studio

